baseURL: "https://lumochift.org"
languageCode: "en-us"
title: "Moch Lutfi Tech blog"
pygmentsstyle: 'monokai'
paginate: 6
theme: novela
social:
  twitter: "https://twitter.com/kaptenupi"
  github: "https://github.com/h4ckm03d"
  instagram: "https://instagram.com/kaptenupi"
taxonomies:
  author: authors
disqusShortname : "codeflowinyou"
comment: true
googleAnalytics : "UA-45950719-1"
